### ISSUE TITLE
Implement RFC0038: Support for CycloneDX and Syft SBoM in Paketo

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/rfcs#176] opened 2022-04-08 17:38 UTC
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0038-cdx-syft-sbom.md)

## Summary

Buildpacks which directly provide a dependency or buildpacks which install application dependencies will support the generation of SBoM in the format of CycloneDX and Syft. Per [CNB RFC#95](https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md), the SBoM documents will live at `<layer>.bom.<ext>.json`, `launch.bom.<ext>.json` and `build.bom.<ext>.json` where `<ext>` will be `cdx` (CycloneDX) or `syft` (Syft).

## Language Family Adoption

* [x] .NET Core: https://github.com/paketo-buildpacks/dotnet-core/issues/628
* [x] Go: https://github.com/paketo-buildpacks/go/issues/524
* [x] Java
* [x] Node.js: https://github.com/paketo-buildpacks/nodejs/issues/496
* [x] PHP: https://github.com/paketo-buildpacks/php/issues/517
* [x] Python: https://github.com/paketo-buildpacks/python/issues/399
* [x] Ruby: https://github.com/paketo-buildpacks/ruby/issues/759
* [x] Web Servers: https://github.com/paketo-community/web-servers/issues/45

**Comment by fg-j** [comment] 2022-07-05 19:26
As discussed in Paketo [slack](https://paketobuildpacks.slack.com/archives/CU8RVQZ1R/p1651688658744609), we've found that SBOMs are not always reproducible documents. This means that buildpack builds sometimes don't produce reproducible images, if one or more SBOMs have been included in the built image.

- The CycloneDX SBOM generated by Syft contains a [`metadata.timestamp`](https://cyclonedx.org/docs/1.3/json/#metadata_timestamp) entry, which is inherently not reproducible. It is an OPTIONAL part of the CycloneDX spec.
- The CycloneDX SBOM generated by Syft also contains a [`serialNumber`](https://cyclonedx.org/docs/1.3/json/#serialNumber), which should be unique "even if the contents of the BOM being generated have not changed over time. The process or tool responsible for creating the BOM should create random UUID's for every BOM generated." The `serialNumber` is an OPTIONAL part of the CycloneDX spec.
##

- the SPDX SBOM generated by Syft contains a [`documentNamespace`](https://spdx.github.io/spdx-spec/document-creation-information/#65-spdx-document-namespace-field) field, which "shall be unique for the SPDX document including the specific version of the SPDX document." It is REQUIRED in the SPDX spec.
- the SPDX SBOM generated by Syft contains a [`created`](https://spdx.github.io/spdx-spec/document-creation-information/#69-created-field) field, which is a timestamp used to "[i]dentify when the SPDX document was originally created". It is a REQUIRED part of the SPDX spec.

The upshot of this is that attaching SBOMs is negatively impacting build reproducibility. One mitigation is to exclude the optional irreproducible fields from the CycloneDX SBOM. But since irreproducible fields are required in the SPDX spec, we'll need to remove SPDX support or find some other crafty way to get around the SPDX documents' irreproducibility.

**Comment by fg-j** [comment] 2022-07-12 21:25
Next steps:
- Write an RFC about omitting optional non-reproducible CycloneDX fields
- Write an RFC about whether to support SPDX in a reproducible way, and how
- Start a conversation with syft about the importance of SBOM reproducibility

**Comment by fg-j** [comment] 2022-07-13 14:40
Filed https://github.com/anchore/syft/issues/1100

**Comment by 06kellyjac** [comment] 2022-07-20 07:00
I raised the issue of non reproducible fields in CycloneDX but they wanted to keep them as required...

https://github.com/OWASP/Software-Component-Verification-Standard/issues/31

So you'll probably need to fill it with dummy data e.g. 1970-01-01 or "semi-accurate" (as-in not the timestamp they want but a relevant enough/still useful timestamp) values using reproducible data like using SOURCE_DATE_EPOCH

**Comment by fg-j** [comment] 2022-07-20 14:47
Thanks for that context, @06kellyjac. I'm a bit confused, since CycloneDX currently marks those non-reproducible fields as optional – but is an OWASP project.

Given that OWASP seems to be of two minds on this, do you think it'd be wiser to a) fill in reproducible data for those CycloneDX fields or b) [remove them for now](https://github.com/paketo-buildpacks/rfcs/pull/220) since they're currently optional?

**Comment by 06kellyjac** [comment] 2022-07-20 15:50
Well it's not even the bureaucracy of the OWASP org that lead to this misalignment. The document was lead by the same person who is the lead/chair on the CycloneDX spec & has developed most of the cyclonedx org's tools and code :sweat_smile: 

https://github.com/OWASP/Software-Component-Verification-Standard/blob/master/OWASP_SCVS-1.0-en.pdf
https://github.com/CycloneDX/cyclonedx-core-java/graphs/contributors
https://cyclonedx.org/about/working-groups/

If they're optional in the spec then I guess we can drop them. Then either the doc will reflect the spec and nothing changes, or the spec will reflect the doc and we'll have to fill it with dummy data as mentioned above

**Comment by fg-j** [comment] 2022-08-02 15:12
#220 Has been approved and merged, meaning there's a path forward for reproducible CycloneDX SBOMs.

**Comment by ForestEckhardt** [comment] 2022-08-02 15:30
@ryanmoran Is finishing Rust necessary seeing as it is still a Community buildpack?

**Comment by ryanmoran** [comment] 2022-08-02 15:35
I don't think so. I can remove it from the list, but I want to leave this issue open until we implement the amendments to this RFC around reproducibility.

**Comment by ForestEckhardt** [comment] 2022-09-06 21:51
Is there any reason we should not close?

**Closed** 2022-09-07 16:24 UTC
